import { BrowserRouter, Routes, Route } from 'react-router-dom';
import '@downpat/ui-components/styles';
import '@downpat/admin-ui/styles';

import { AuthProvider } from './components/AuthProvider';
import { Layout } from './components/Layout';
import { ProtectedRoute } from './components/ProtectedRoute';

// Pages
import { Home } from './pages/Home';
import { Login } from './pages/Login';
import { ExerciseBrowser } from './pages/ExerciseBrowser';
import { Conversation } from './pages/Conversation';
import { AdminDashboard } from './pages/admin/Dashboard';
import { ExerciseListPage } from './pages/admin/ExerciseListPage';
import { ExerciseEditor } from './pages/admin/ExerciseEditor';

/**
 * =============================================================================
 * MOVE TO: New @downpat/react package
 *
 * DECISION: All DownPat routes are namespaced under /downpat to avoid
 * collisions with host application routes:
 *   /downpat/exercises        - Exercise browser
 *   /downpat/exercises/:slug  - Conversation
 *   /downpat/admin            - Admin dashboard
 *   /downpat/admin/exercises  - Exercise list
 *   /downpat/admin/exercises/new
 *   /downpat/admin/exercises/:slug/edit
 *   /downpat/admin/test/:slug
 *
 * DECISION: Create new @downpat/react package that provides route configs
 * via a builder function. Admin routes are mandatory (no exercise creation
 * without admin). Apps should be able to do:
 *
 *   import { createDownpatRoutes } from '@downpat/react';
 *
 *   const downpatRoutes = createDownpatRoutes({
 *     authWrapper: ProtectedRoute,      // App's auth component
 *     adminAuthWrapper: AdminRoute,     // App's admin auth (or same as above)
 *     basePath: '/downpat',             // All routes under this path (default)
 *   });
 *
 *   // Then spread into Routes:
 *   <Routes>
 *     <Route element={<Layout />}>
 *       {downpatRoutes}
 *       {/* App's own routes */}
 *     </Route>
 *   </Routes>
 *
 * The Layout, AuthProvider, and ProtectedRoute should STAY in example-app
 * as they are app-specific (auth, navigation, styling).
 * =============================================================================
 */
function App() {
  return (
    <BrowserRouter>
      <AuthProvider>
        <Routes>
          <Route element={<Layout />}>
            {/* KEEP: Public routes are app-specific */}
            <Route path="/" element={<Home />} />
            <Route path="/login" element={<Login />} />

            {/*
             * MOVE TO: @downpat/react
             * All these routes will be generated by createDownpatRoutes().
             * Page components stay in ui-components/admin-ui, but routing
             * config comes from @downpat/react.
             *
             * TODO: Update paths to /downpat/* namespace:
             *   /exercises        → /downpat/exercises
             *   /exercises/:slug  → /downpat/exercises/:slug
             *   /admin            → /downpat/admin
             *   /admin/exercises  → /downpat/admin/exercises
             *   etc.
             */}
            {/* Protected routes - Subscribers */}
            <Route
              path="/exercises"
              element={
                <ProtectedRoute>
                  <ExerciseBrowser />
                </ProtectedRoute>
              }
            />
            <Route
              path="/exercises/:slug"
              element={
                <ProtectedRoute>
                  <Conversation />
                </ProtectedRoute>
              }
            />

            {/* Protected routes - Admin only */}
            <Route
              path="/admin"
              element={
                <ProtectedRoute requireAdmin>
                  <AdminDashboard />
                </ProtectedRoute>
              }
            />
            <Route
              path="/admin/exercises"
              element={
                <ProtectedRoute requireAdmin>
                  <ExerciseListPage />
                </ProtectedRoute>
              }
            />
            <Route
              path="/admin/exercises/new"
              element={
                <ProtectedRoute requireAdmin>
                  <ExerciseEditor />
                </ProtectedRoute>
              }
            />
            <Route
              path="/admin/exercises/:slug/edit"
              element={
                <ProtectedRoute requireAdmin>
                  <ExerciseEditor />
                </ProtectedRoute>
              }
            />
            <Route
              path="/admin/test/:slug"
              element={
                <ProtectedRoute requireAdmin>
                  <Conversation isAdminTest />
                </ProtectedRoute>
              }
            />
          </Route>
        </Routes>
      </AuthProvider>
    </BrowserRouter>
  );
}

export default App;
